### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MatrixInversePSD'

### ISSUE THREAD

**Issue by alinoleumm** [mkusner/grammarVAE#21]
I get this error while trying to run bayesian optimization
(I've tried to import other classes from 'molecule_optimization/simulation1/grammar/sparse_gp_theano_internal.py' and it didn't cause such an error, so I guess that is not an import error)

**Comment by mkusner** [comment]
Hey alinoleumm! Did you install Theano using the Theano-master folder in the repo? here: https://github.com/mkusner/grammarVAE/tree/master/Theano-master

**Comment by alinoleumm** [comment]
yep

**Comment by mkusner** [comment]
Hmm, can you tell me what you get when you call:
```
>>> import theano
>>> theano.__version__
```

**Comment by alinoleumm** [comment]
![image](https://user-images.githubusercontent.com/23420630/55725410-74bcbe00-5a2f-11e9-97eb-13a78912e77f.png)

**Comment by mkusner** [comment]
I think this is the issue! It looks like you have an earlier installation of theano that isn't a dev version. The version in the repo is called
`0.8.0.dev-unknown-git`
So if you uninstall theano then reinstall the Theano-master version in the repo, this error should go away.

**Comment by alinoleumm** [comment]
yes, that was the issue, thanks!

**Comment by jinzhezhang** [comment]
Duplicate of #21

Hi,

I think this issue was raised previously. However, the situation about theano repo is kind of confusion. Sorry if this sounds stupid to ask: how exactly can we install this perticular dev version of theano? I checked a few version of theano release and none of them has a MatrixInversePSD() method

Thanks!

**Comment by mkusner** [comment]
So you need to install the version of theano included in the repository: https://github.com/mkusner/grammarVAE/tree/master/Theano-master

This version has a MatrixInversePSD() method

**Comment by jinzhezhang** [comment]
Thanks for the swift reply! The issue is solved now! 

Just to be clear for anyone potentially has the same issue, this is the workaround that I found:

Download files of the whole project of https://github.com/mkusner/grammarVAE/, Theano_master is one subdirectory of the project.

Then pip install xxxxx/grammarVAE/Theano_master where xxxxx is the path of the project

In this case, pip is able to recognize it's a 0.8.0 version.
