### ISSUE TITLE
Failing to run run_bo.py

### ISSUE THREAD

**Issue by ParthaEth** [mkusner/grammarVAE#23]
Hi I have to following error occuring while trying to run run_bo.py character VAE for molecules.

File "run_bo.py", line 164, in <module>
    current_log_P_value = Descriptors.MolLogP(MolFromSmiles(valid_smiles_final[ i ]))
  File "/is/ps2/pghosh/.anaconda/grammar_RAE/lib/python2.7/site-packages/rdkit/Chem/Crippen.py", line 170, in <lambda>
    MolLogP = lambda *x, **y: rdMolDescriptors.CalcCrippenDescriptors(*x, **y)[0]
ValueError: Sanitization error: Explicit valence for atom # 17 O, 4, is greater than permitted

I suspect that it is trying to evaluate the quality of a molecule that is not physically possible. However this should be ignored with highest evaluation cost. I have a different verwion of RDKIT (2017.09.3). Is that a problem? How may I fix this?

**Comment by mkusner** [comment]
Right, this is an rdkit error. The issue is exactly as you said: the SMILES
creates an 'unsanitized' molecule (as it runs
MolFromSmiles(valid_smiles_final[ i ]) ), but then when you calculate the
descriptors you need to sanitize it and there's a valence error, meaning
it's not physically valid.

Try calling:

mol = MolFromSmiles(valid_smiles_final[ i ])
Chem.SanitizeMol(mol)
current_log_P_value = Descriptors.MolLogP(mol)

You may need two SanitizeMol calls as described here:
https://sourceforge.net/p/rdkit/mailman/message/36454943/

In general check out stackoverflow posts and similar resources  that
address Sanitization error. There seems to be a lot of info about this.

**Comment by ParthaEth** [comment]
HI  @mkusner That was fixed by changing RDKIT version to 2016.03.3. However I get now a different error that looks like the following.

Now I have no experience with RDKIT or chemistry in general. I would like to simply evaluate my generative model on a structured problem such as molecule generation. it is expected that some of the molecules generated are physically not possible so we should be "try: except-ing" such scenarios?

So what would be a fair value assignment to the impossible molecules? Like `current_log_P_value=None` when `Descriptors.MolLogP(MolFromSmiles())` fails for wahtever reason?

"Traceback (most recent call last):
  File "run_bo.py", line 163, in <module>
    current_log_P_value = Descriptors.MolLogP(MolFromSmiles(valid_smiles_final[ i ]))
  File "/is/ps2/pghosh/.anaconda/grammar_RAE/lib/python2.7/site-packages/rdkit/Chem/Crippen.py", line 158, in <lambda>
    MolLogP=lambda *x,**y:rdMolDescriptors.CalcCrippenDescriptors(*x,**y)[0]
RuntimeError: Pre-condition Violation
	no bonds
	Violation occurred on line 252 in file Code/GraphMol/ROMol.cpp
	Failed Expression: getNumBonds() > 0
	RDKIT: 2016.03.3
	BOOST: 1_56"

**Comment by mkusner** [comment]
It looks like you have a molecule without any bonds such as 'C'. Here's my
suggestion:
- install rdkit from anaconda as described here:
https://www.rdkit.org/docs/Install.html
- if the problem still persists either use a try/catch and call this
molecule invalid if you go to the catch statement OR searching/asking on
rdkit forums to get more info on these errors. I'm sorry but I've never
seen these errors before!
