### ISSUE TITLE
Convert Exception

### ISSUE THREAD

**Issue by chao1224** [mkusner/grammarVAE#3]
I got this exception when I ran the `encode_decode_zinc.py`
```
TypeError: Failed to convert object of type <class 'theano.tensor.var.TensorVariable'> to Tensor. Contents: argmax. Consider casting elements to a supported type.
```

So I'm wondering if this is cause by different Tensorflow and Keras version. Can you specify what version you are using?

BTW. I tested both Keras and Tensorflow as 1.2.1

**Comment by mkusner** [comment]
Hey Shengchao! Are you sure you're using tensorflow? It looks like you're
using theano, which we don't have support for yet.

On Jul 31, 2017 5:30 PM, "Shengchao Liu" <notifications@github.com> wrote:

I got this exception when I ran the encode_decode_zinc.py

TypeError: Failed to convert object of type <class
'theano.tensor.var.TensorVariable'> to Tensor. Contents: argmax.
Consider casting elements to a supported type.

So I'm wondering if this is cause by different Tensorflow and Keras
version. Can you specify what version you are using?

BTW. I tested both Keras and Tensorflow as 1.2.1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mkusner/grammarVAE/issues/3>, or mute the thread

**Comment by chao1224** [comment]
Sorry, I forgot to set the KERAS_BACKEND.
Just found the Keras and TF version in `requirements.txt`, fixed.
Thanks.
